name: Process Biographies

on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'Number of biographies to process'
        required: true
        default: '10'
        type: string
  schedule:
    # Run every 1.5 hours (90 minutes)
    - cron: '0 */1 * * *' 

jobs:
  process-biographies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install python-dotenv google-generativeai pydantic requests; fi
      
      - name: Create .env file with API key
        run: |
          echo "GOOGLE_GEMINI_API_KEY=${{ secrets.GOOGLE_GEMINI_API_KEY }}" > .env
        
      - name: Process biographies
        run: |
          # If triggered by schedule, process 2500 biographies, otherwise use the input limit
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            python src/054-structure-gemini-async.py 10000
          else
            python src/054-structure-gemini-async.py ${{ github.event.inputs.limit }}
          fi
      
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Commit and push changes
        run: |
          # pull latest changes to avoid merge conflicts
          git pull origin main
          # Add structured biographies to the repository
          git add data/structured_biographies/
          # Only commit if there are changes
          git diff --quiet && git diff --staged --quiet || git commit -m "Add structured biographies [automated]"
          git push