name: Process Biographies

on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'Number of biographies to process'
        required: true
        default: '10'
        type: string

jobs:
  process-biographies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install python-dotenv google-generativeai pydantic requests; fi
      
      - name: Create .env file with API key
        run: |
          echo "GOOGLE_GEMINI_API_KEY=${{ secrets.GOOGLE_GEMINI_API_KEY }}" > .env
        
      - name: Process biographies
        run: |
          # Run the script with the specified limit
          python src/053-structure-gemini.py ${{ github.event.inputs.limit }}
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Commit and push changes
        run: |
          git add data/structured_biographies/
          # Only commit if there are changes
          git diff --quiet && git diff --staged --quiet || git commit -m "Add structured biographies [automated]"
          git push