name: Scrape Book Pages and Biographies

on:
  workflow_dispatch:
    inputs:
      resume_book_id:
        description: 'Book ID to scrape'
        required: true
        default: '2001'
      resume_page:
        description: 'Page number to resume scraping from'
        required: false
        default: '0'
  schedule:
    - cron: '0 */4 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      BOOK_IDS: "1981 1977 1969 1967 1963 1957 1955 1953 1945 1943 1939 1933 1925 1918"
      CURRENT_BOOK_ID: 1981

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Get current book ID
        id: get-book-id
        run: |
          if [ -f .current_book_id ]; then
            CURRENT_BOOK_ID=$(cat .current_book_id)
          else
            CURRENT_BOOK_ID=${{ env.CURRENT_BOOK_ID }}
          fi
          echo "CURRENT_BOOK_ID=$CURRENT_BOOK_ID" >> $GITHUB_ENV
          echo "Current book ID: $CURRENT_BOOK_ID"

      - name: Run scraper
        run: |
          python src/00-fetch_page_text_all_books_github_actions.py "${{ env.CURRENT_BOOK_ID }}" --resume_page "0"

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Update book ID
        id: update-book-id
        run: |
          BOOK_IDS=(${{ env.BOOK_IDS }})
          CURRENT_BOOK_ID=${{ env.CURRENT_BOOK_ID }}
          for i in "${!BOOK_IDS[@]}"; do
            if [ "${BOOK_IDS[$i]}" == "$CURRENT_BOOK_ID" ]; then
              if [ $i -lt $((${#BOOK_IDS[@]} - 1)) ]; then
                NEXT_BOOK_ID=${BOOK_IDS[$((i + 1))]}
                echo $NEXT_BOOK_ID > .current_book_id
                echo "Next book ID: $NEXT_BOOK_ID"
                echo "CURRENT_BOOK_ID=$NEXT_BOOK_ID" >> $GITHUB_ENV
                break
              fi
            fi
          done
